### ISSUE TITLE
Add Configuration Option for "Related Content" Title

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#113]
Allow users to customize the title of the block "Related Content" in the CERES toolkit settings page

**Comment by elizoller** [comment]
@sarahjeansweeney Do you want this text to display as part of the loading and no results messages or just the block title?
Currently while content is loading it says "Looking for related content..."
when no results are retrieved it says "No related content was found."

**Comment by sarahjeansweeney** [comment]
Yeah, if the custom text could be carried forward to other places it's mentioned, that would be great.
