### ISSUE TITLE
Function undined: `write_log()`

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-plugin#123]
Hi Eli -

Okay - figured it out.  FINALLY.

It is this line:

https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/blob/master/inc/browse.php#L47

Do you have a custom `write_log()` function defined somewhere else in your environment ?  I don't think that `write_log()` is part of WordPress core.  

If I use the `error_log` (which is part of PHP) it works correctly.

I think we either need to define `write_log()` in the plugin (if you want to use it) or switch it to `error_log()`.  I am guessing you have that function available somewhere via another plugin.

Let me know what you think.

Damon

**Comment by elizoller** [comment]
I have `write_log` defined in theme but its for debugging purposes only so should really be removed
Sorry for that!

**Comment by thornomad** [comment]
Always feels good to figure something out.
