### ISSUE TITLE
Repeating Titles

### ISSUE THREAD

**Issue by s-payne** [NEU-Libraries/drs-toolkit-wp-plugin#124]
On the ECDA Website, pages have titles that are appearing twice. The ECDA team would like the title to only appear once, but in the backend it is unclear why the title is appearing twice. 
![screen shot 2018-01-23 at 11 12 15 am](https://user-images.githubusercontent.com/30182432/35286808-f4d9aaa0-002e-11e8-870e-d739c5400694.png)
![screen shot 2018-01-23 at 11 12 29 am](https://user-images.githubusercontent.com/30182432/35286816-f812ac6c-002e-11e8-9116-adc05eaa5009.png)

**Comment by s-payne** [comment]
I was able to fix this by going to customize, layout, single page, and then under "show title bar," selecting no.

**Comment by sarahjeansweeney** [comment]
👍 👍
