### ISSUE TITLE
Menu Text Run-off

### ISSUE THREAD

**Issue by s-payne** [NEU-Libraries/drs-toolkit-wp-plugin#125]
On the ECDA [website](https://ecda.northeastern.edu/) longer text on dropdown menus runs off the dropdown box.  There doesn't seem to be a way to expand the size of the dropdown box so longer titles don't run off. 

![screen shot 2018-01-23 at 11 20 48 am](https://user-images.githubusercontent.com/30182432/35287069-8fe510de-002f-11e8-882d-74c5f4978087.png)

**Comment by sarahjeansweeney** [comment]
Moved to https://github.com/NEU-DSG/toolkit_requests/issues/95
