### ISSUE TITLE
Homepage slider not working

### ISSUE THREAD

**Issue by saraheconnell** [NEU-Libraries/drs-toolkit-wp-plugin#129]
The slider on our class site homepage (https://litdigitaldiversity.northeastern.edu) has stopped showing images:
<img width="1183" alt="screen shot 2018-10-24 at 12 04 50 pm" src="https://user-images.githubusercontent.com/8170384/47445352-b65df300-d786-11e8-8796-45d87b641957.png">
I've confirmed this happens in both Safari and Chrome. It's not something I did, I think, because that page hasn't been changed since February. 
Ashley and I inspected this and she said this screenshot might be helpful:
<img width="1237" alt="screen shot 2018-10-24 at 12 08 01 pm" src="https://user-images.githubusercontent.com/8170384/47445399-d4c3ee80-d786-11e8-8ec9-50e92065fd6c.png">
Just let me know if you need me to test anything!

**Comment by dgcliff** [comment]
@saraheconnell The slider shortcode cached a bad DRS response. I've updated the page to invalidate it, and it appears to have been resolved.
