### ISSUE TITLE
Update hardcoded fallback DPLA image

### ISSUE THREAD

**Issue by patrickmj** [NEU-Libraries/drs-toolkit-wp-plugin#136]
There's a hardcoded fallback image for DPLA items that don't have a thumbnail. That's currently broken. It would be nice if there's a way to check what the original format is, and give an appropriate thumbnail on that switch.

**Comment by nestochan** [comment]
![logo](https://user-images.githubusercontent.com/2441612/48732147-d01b1a80-ec0c-11e8-95ee-78e8194e0817.png)

https://web.archive.org/web/20171114204029/https://dp.la/info/wp-content/themes/berkman_custom_dpla/images/logo.png

@patrickmj is this it?

**Comment by patrickmj** [comment]
Probably. I'd like to find something that's more square if they have something, though, just for the layout.


Patrick


Patrick Murray-John

Associate Director for Systems

Digital Scholarship Group, Snell Library

Northeastern University

p.murray-john@northeastern.edu

________________________________
