### ISSUE TITLE
Add a separate input for URL for single item search

### ISSUE THREAD

**Issue by patrickmj** [NEU-Libraries/drs-toolkit-wp-plugin#137]
It looks like the technique for DPLA of copying the ID of an item and searching for that within the toolkit no longer works (searching DPLA's site directly for an ID gives no results). Regardless, it'll be much more user-friendly to just let people paste the whole URL into a separate input and have the plugin parse out the ID and stuff it into the shortcode without doing the search.

**Comment by nestochan** [comment]
https://web.archive.org/web/20171114204029/https://dp.la/info/wp-content/themes/berkman_custom_dpla/images/logo.png
