### ISSUE TITLE
Auto-rotate not working in gallery slider

### ISSUE THREAD

**Issue by saraheconnell** [NEU-Libraries/drs-toolkit-wp-plugin#147]
My students have discovered that the auto-rotate option does not work in the gallery slider; no matter what items I use or settings I try, the slider doesn't auto-rotate. I talked with Patrick about this and it looks like the issue has been happening for at least a couple of years.

**Comment by patrickmj** [comment]
Should be fixed in b143080b453a8775ae679f7d2da060e35cc14c71
