### ISSUE TITLE
"myNortheastern" in CERES footers

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/drs-toolkit-wp-plugin#160]
Similar to the [Cerberus ticket](https://github.com/NEU-Libraries/cerberus/issues/1176), it looks like the CERES footer was not updated during the push to update "myNEU" to "myNortheastern" in all university branding (though I could have sworn it was done in CERES!):

![2018-12-17_1539](https://user-images.githubusercontent.com/4663073/50114335-47df6380-0212-11e9-8c45-dc2d44015eb2.png)

The existing sites should be changed to "myNortheastern" and the settings for future installs should be updated, as well.

**Comment by patrickmj** [comment]
Thanks. this gives an excuse to refactor a line in the theme that's been on my hit list for a while: https://github.com/NEU-Libraries/drs-toolkit-wp-theme/blob/develop/functions.php#L127

**Comment by patrickmj** [comment]
@sarahjeansweeney Do you happen to know if there's guidance about listing the copyright year? right now it says copyright the current year, which has always struck me as weird, but I don't have any strong opinions on it. Just makes sense to slap in the practice they want while I'm in there. Thanks!

**Comment by patrickmj** [comment]
Fixed in https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/79c74f52add62fe4a5a077a5deff4ef513a25c54 but want to leave open until I know if the copyright year question is an actual thing.

**Comment by sarahjeansweeney** [comment]
@patrickmj The Brand Guide from External Affairs may have more information about how copyright is handled: https://brand.northeastern.edu/

**Comment by patrickmj** [comment]
Thanks. I don't see any pertinent info there, so this will go up as part of v2.0
