### ISSUE TITLE
Configuration based on Sets instead of Collections

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#18]
Change the configuration of the site to handle sets or collections as starting urls

**Comment by sarahjeansweeney** [comment]
Related to https://github.com/NEU-Libraries/cerberus/issues/725 and https://github.com/NEU-Libraries/cerberus/issues/726

**Comment by elizoller** [comment]
Users can now enter a set URL instead of a collection URL in the plugin settings

**Comment by sarahjeansweeney** [comment]
:+1:
