### ISSUE TITLE
Multiple map shortcodes on same page conflict: all items display on one map

### ISSUE THREAD

**Issue by AmandaRust** [NEU-Libraries/drs-toolkit-wp-plugin#205]
Related to NEU-Libraries/toolkit_requests#111 ?

A page with two different map shortcodes is attempting to display all items on one map.
https://publichistory.library.northeastern.edu/megan-test/

There is extra whitespace on the page, so it looks like there's some sort of frame happening at the bottom, where we'd expect the second map? On the back end (second screenshot), you'll see that there are two map shortcodes. The first map should have 6 locations and the 2nd should have 7 locations. 

![image](https://user-images.githubusercontent.com/10200332/45429775-f43d0700-b671-11e8-9ae1-c2df902cdb43.png)

![image](https://user-images.githubusercontent.com/10200332/45429849-1898e380-b672-11e8-8547-1f403d66e52d.png)

**Comment by patrickmj** [comment]
Looks duplicate with #184 
Closing as duplicate
