### ISSUE TITLE
Hello World Post

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#31]
hello world post is showing up in related content - not sure if this is an issue with the search or if the search is working and the reason its showing up is because WP thinks its a valid search result.
or if we should just be deleting the hello world post in the install process?
<img width="1260" alt="2015-09-23_1330" src="https://cloud.githubusercontent.com/assets/5439169/10078347/45bf145e-62b2-11e5-81ca-efbaa0cc6fd9.png">

**Comment by elizoller** [comment]
WP actually thinks Hello world is a valid search result 
This is because of the 'world' in the title of the blog post haha and the search query containing the word 'world'

**Comment by sarahjeansweeney** [comment]
That "Hello World" post is there by default? Can we delete it as part of the theme setup, or should we recommend users delete it themselves?

**Comment by elizoller** [comment]
I can delete it when I setup the site. That is no problem.
