### ISSUE TITLE
Labelling for Related Content

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#32]
How to make it clearer to the user the difference between the DRS search results and the related content

**Comment by sarahjeansweeney** [comment]
I think this might be completed with the new custom label.

**Comment by elizoller** [comment]
Yes! fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/177d511d9a6468a8a0d075a4e87e1a2030325af8
