### ISSUE TITLE
Options for Single Item View

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#33]
Allow users to choose which metadata fields show up on the item level display.

**Comment by elizoller** [comment]
@sarahjeansweeney can you help me with a list of common MODS elements to give to users as options for this?

**Comment by sarahjeansweeney** [comment]
Sure. Are you going to allow them to select subelements, or can they only choose what top level elements to display?

**Comment by elizoller** [comment]
I was thinking top level elements like title, description, creator, note kind of thing

**Comment by sarahjeansweeney** [comment]
Sounds good. Here are the common top level elements:

titleInfo
name
typeOfResource
genre
originInfo
language
physicalDescription
abstract
tableOfContents
note
subject
relateditem
identifier
location
accessCondition
part
extension

I only omitted two top level fields: targetAudience is rarely used and recordInfo shouldn't display.

**Comment by elizoller** [comment]
Thanks!

**Comment by elizoller** [comment]
@sarahjeansweeney So I'm realizing that I don't get the MODS node name but the MODS display name for this. Ie. the JSON will say something like 
```Title: [
"Orbis Terrae Compendiosa Descriptio"
],
Contributor: [
"Mercator, Gerard, 1512-1594 (Cartographer)<br/>Mercator, Rumold, approximately 1545-1599 (Cartographer)"
],
Publisher: [
"Duisburg"
],```
so what kind of label possibilities are there for these MODS elements? I've included what I think they map to below (some I was not sure) but it occurs to me that there is probably a lot of uniqueness that could be passed in that label field - is that correct? If so, I think this might not be the best way to do this.

titleInfo -> Title
name -> Creator, Contributor, Publisher
typeOfResource -> Type of Resource
genre -> Genre
originInfo -> ?
language -> Language
physicalDescription -> ?
abstract -> Abstract/Description
tableOfContents -> ?
note -> Notes
subject -> Subjects and keywords
relateditem -> Related item
identifier -> Identifier
location -> Location
accessCondition -> Access Condition
part -> ?
extension -> ?

**Comment by sarahjeansweeney** [comment]
I think the display labels are actually controlled by the MODS display gem, which I know for sure splits names with the "author" role into creator fields and every other role into the contributor field (so that's why you're seeing the cartographers under the "Contributor" label in the JSON). 

I think this is the full list of possible display labels from the MODS gem: https://github.com/NEU-Libraries/mods_display/blob/master/config/locales/en.yml. If the JSON is being generated from the MODS display gem and not the original MODS, then I think we can safely rely on the labels being passed by the gem.

**Comment by elizoller** [comment]
perfect. thanks!

**Comment by elizoller** [comment]
What should I be looking for in originInfo, part, and extension?

**Comment by sarahjeansweeney** [comment]
Are you asking about what labels you should expect, or what MODS fields to look for in each of those elements?

**Comment by elizoller** [comment]
the labels I mean sorry

**Comment by elizoller** [comment]
pushed up for the labels listed above. will do the originInfo, part, and extension (and other labels we stumble across later on) next week.

**Comment by elizoller** [comment]
@sarahjeansweeney for originInfo, part, and extension, this is what I came up with looking at the code for cerberus:
- originInfo: place (city_term and state_term), publisher, copyright, date_created, date_issued
- extension: scholarly object (category, department, degree, course_info)
does that seem right? at least for a starting point

**Comment by sarahjeansweeney** [comment]
orginInfo looks good to me. 
The extension field for scholarly objects is mostly invisible to users in the display, so don't worry about it.
I may be missing it, but looking through the list of fields in the mods display, I'm not sure the part fields are coming through at all.

**Comment by elizoller** [comment]
not seeing anything in mods display for part. so i'll exclude part and extension for now and just work on origin info. we can address it again later if need be. thanks

**Comment by elizoller** [comment]
closed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/b269b69fb12ee4c87e2adf6d271e2689cc2cc52b
