### ISSUE TITLE
Item Page Crashes Chrome on iPad

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#36]
This happens only on liblab.neu.edu/drstest on item pages on Abbie's iPad
Gremlins?

**Comment by elizoller** [comment]
Still can't reproduce this. Even on my ipad and iphone.

**Comment by sarahjeansweeney** [comment]
Let's test it on one more iPad, and if we still can't replicate it we can close the ticket. Do we know anyone else who has one?

**Comment by nestochan** [comment]
I got it to crash on my Ipad: showed @elizoller

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/commit/01e11753e7f657f70c54ff0cdbb1ae3aae4be101
thanks @nestochan for discovering the issue
ipad crashed when trying to load a tif (which is understandable because its a 200+MB file) which was being used for the zoom feature. switch it to using thumbnail 4 and 5 instead of thumbnail 5 and master to accommodate for this.
