### ISSUE TITLE
Resize images in shortcode

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#5]
Resize photos or access different sized options from without galley slider function.
Potential options
   - allow user to set max-height of slider
   - allow user to select which thumbnail they use from the DRS

**Comment by elizoller** [comment]
Have dropdown for user to select image size from DRS thumbnail options like
![untitled](https://cloud.githubusercontent.com/assets/5439169/9663197/3a70fdec-5231-11e5-97d6-d1a6901e0965.png)

**Comment by elizoller** [comment]
Looking into this more, I think there are a few different routes we can go.
1. provide dropdown with image sizes from DRS (auto-generated thumbnails only). for slider and tiles, this would be a gallery-wide setting.
2. provide dropdown with images sizes from DRS (auto-generated thumbnails plus any additional derivatives - sometimes have small, medium, and large. would be more work because you'd have to actually get the images from the DRS and print their size out to the screen). for slider and tiles, this would not be a gallery-wide setting since not all images have the same (or any) derivatives so this would require a significant change to the way these shortcodes work.
3. provide custom size option. this would allow a user to enter a width or height and have the opposite dimension adjusted automatically to maintain the ratio of the image. for slider and tiles, this could be a gallery-wide setting. it would require some extra logic to figure out which image to grab from the DRS in the first place depending upon the width/height the user inputted (ie. if they want an image that is 200px tall, we don't need to grab the largest thumbnail because it would be overkill).
4. provide cropping. this is by far the most complex. wordpress has built-in functionality in the media library to crop any image. i think we could potentially leverage that functionality but it would require some serious reconfiguring in order to clone an image from the DRS into the media library (I don't think it's necessarily a bad idea to think of using the media library as storage for this because I don't think people will crop that many images) and store it in a way that it could be retrieved any time that pid is called into action (or would it be specific to one single shortcode - in which case it would be even more complex and require us to start to create identifiers for each shortcode). This would also require substantial work regarding for slider and tiles because it would be per-image not gallery-wide. I'm not sure how many users would use a cropping function. I would say this option would be a 2.0 feature. Unless any has other ideas on how this could work?

**Comment by sarahjeansweeney** [comment]
1 and 3 sound like the best options to me. Both seem to be gallery wide, and won't require "significant" work. I suggest starting with option one. If more customization is required, we can try option 3.
