### ISSUE TITLE
.caption .text-area still present when deselcted

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-plugin#74]
If you don't select any metadata for the browse settings it still loads the elements ... just without any text, causing white space.  The same whitespace phenomenon is on the search page as well. 

<img width="1185" alt="screen shot 2016-03-05 at 6 46 40 am" src="https://cloud.githubusercontent.com/assets/124717/13548159/63e09716-e29e-11e5-94c2-ebfa6b4a4652.png">

**Comment by elizoller** [comment]
I think I introduced this bug the other day when I refactored settings. I'll fix it tomorrow

**Comment by elizoller** [comment]
I'm not sure what you mean by the white space on the search page. 
This is what I'm seeing
<img width="914" alt="screen shot 2016-03-06 at 4 28 52 pm" src="https://cloud.githubusercontent.com/assets/5439169/13557191/a9f59f06-e3b8-11e5-82f0-93d430d11e2f.png">

**Comment by thornomad** [comment]
I was looking at this:

<img width="914" alt="a9f59f06-e3b8-11e5-82f0-93d430d11e2f" src="https://cloud.githubusercontent.com/assets/124717/13572353/b430b84a-e42e-11e5-9d96-6ab95adc14d7.png">

But it is different than the `browse` page ... on the `browse` page the elements are present but the test is empty;  this is just empty space.  Maybe it's be design on this one ?

**Comment by elizoller** [comment]
Yeah they are meant to be full width rows in the search display. I can align the 'view more' button to a different place.

**Comment by thornomad** [comment]
Okay - no worries.

**Comment by elizoller** [comment]
Closing this because I think search is displaying as expected/I hope no one will turn off all the metadata on the search ?
