### ISSUE TITLE
Can we add: `niec_lendsitselftoclassifiers` & `niec_lendsitselftouseofspace`

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-plugin#77]
I noticed those two facets were missing; do they need to be added to the backend somewhere first?  I tried adding them to the plugin myself but it's throwing an error when reaching out via the API.

**Comment by elizoller** [comment]
Do you have an example of a record that has this value?

**Comment by thornomad** [comment]
Yea - check out: 

https://repository.library.northeastern.edu/files/neu:rx917x47c

Also, if you browse here you can facet by them ... not all records have it:

http://www.interpretereducation.org/tim/terptalks/#fq=niec_lendsitselftoclassifiers%3AMinimal

Damon

**Comment by elizoller** [comment]
These have not been defined as values to faceted on in the DRS so they aren't coming through the search API response as facets. They'll still coming through attached to each item. It should be an easy fix to make them facets. I'll check with David about it.

**Comment by thornomad** [comment]
Okay - glad there is an answer to the mystery.

**Comment by thornomad** [comment]
Interesting - want me to check and make sure they still want to use them as facet-able items?  I noticed not everything is classified that way ...

**Comment by elizoller** [comment]
If you want. Not a big deal to add it to the DRS. Ticket: https://github.com/NEU-Libraries/cerberus/issues/924

**Comment by thornomad** [comment]
Great - let's just do it!

**Comment by thornomad** [comment]
Thanks for getting this sorted, by the way.  I see those two items now in the my facet options!
