### ISSUE TITLE
[bug] zoom elevate causing a problem with display of this item

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-plugin#85]
Was just clicking and testing and I came across this DRS item (and so far only this item) that is showing a display bug of some sort ... not sure why this is happening but perhaps is related to zoom elevate (am thinking maybe that because that's what shows up in the inspector)?  Here is the [link to the live page](http://www.test.interpretereducation.org/tim/terptalks/item/neu:rx918173s/).

I thought maybe I had done something to cause this but I reset it back to your latest revision (before I changed anything lately) and the problem persists.

This is the only item where I get this display issue ... not sure why!

<img width="1224" alt="screen shot 2016-03-20 at 7 22 58 am" src="https://cloud.githubusercontent.com/assets/124717/13904882/9c4d96b0-ee6c-11e5-819d-ed60af3d4cd2.png">

**Comment by elizoller** [comment]
For some reason this object has two canonical objects- a video file and an image. So I'm going to change it so it only processes the first canonical object since this is how the repository treats the canonical object.

**Comment by thornomad** [comment]
Excellent - thanks!  That fixed it.
