### ISSUE TITLE
"Video File" download button does not seem to work in Safari

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-plugin#88]
In Firefox and Chrome (on Mac) the "Video File" download button prompts to have the user download the video file ... however, on Safari, it tries to play it in the browser (I can't ever actually get it to play either).

I believe if you change the `Content-Disposition` header from `inline` to `attachment` if that would solve the issue ... as I believe `inline` asks the browser to attempt to open it (if possible) and `attachment` says "download away"!

**Comment by elizoller** [comment]
The downloads link is being created from the DRS which is feeding the content datastream from Fedora. I'm going to look into it further from the DRS perspective.

**Comment by thornomad** [comment]
HI Eli - just wanted to check on this item ... I've send the staging site over to the NIEC folks for beta testing and everyone came back with the same Safari problem: video file won't download.  Any luck changing the `Content-Disposition` ?

**Comment by elizoller** [comment]
I need to check in with David on this. The download links come from the repository so I think something needs to be changed on that end. I realize this may be holding you up so I've temporarily created a fix that passes the content-disposition with a php header. I'm hoping we'll be able to find a solution so the link itself will pass that information but this should do for now.

**Comment by thornomad** [comment]
Was that working for you on your end now in Safari ?

You have what looks like a hard-coded URL in the code still:

https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/blob/master/inc/item.php#L82

I haven't had a chance to try it -- was just looking at the pull.

**Comment by elizoller** [comment]
Fixed base url and yes it works for me in Safari

**Comment by thornomad** [comment]
I'm still having trouble getting this to work -- maybe it's our PHP settings on this server.  What do you think?

http://www.test.interpretereducation.org/tim/terptalks/item/neu:rx917x48n/

If you click the download link it is just returning an error inside an MP4 file ... which reads:

```<br />
<b>Fatal error</b>:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 220200960 bytes) in <b>/home2/nciec/public_html/test.interpretereducation.org/wp-content/plugins/drs-tk/templates/download.php</b> on line <b>13</b><br />```

Does that same `pid` work on your installation ?

**Comment by nestochan** [comment]
wp-settings.php may be where that parameter cab be adjusted.

ě



On Mon, Apr 11, 2016 at 9:59 PM -0700, "Damon Timm" <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm still having trouble getting this to work -- maybe it's our PHP settings on this server. What do you think?

http://www.test.interpretereducation.org/tim/terptalks/item/neu:rx917x48n/

If you click the download link it is just returning an error inside an MP4 file ... which reads:

<br />
<b>Fatal error</b>: Allowed memory size of 268435456 bytes exhausted (tried to allocate 220200960 bytes) in <b>/home2/nciec/public_html/test.interpretereducation.org/wp-content/plugins/drs-tk/templates/download.php</b> on line <b>13</b><br />

Does that same pid work on your installation ?

-

**Comment by elizoller** [comment]
Allowed memory size is almost always a settings issue, remedied by wp-settings.php or php.ini settings

That particular file isn't working for me either.
But I tested with `neu:rx918120r` and `neu:rx918173s` without issue. I'll look into it some more.

**Comment by elizoller** [comment]
`neu:rx917x48n` must be huge - I'm getting a similar error
```PHP Fatal error:  Allowed memory size of 373293056 bytes exhausted (tried to allocate 327733248 bytes) in /Users/beekerz/Sites/wordpress/wp-content/plugins/drs-tk/templates/download.php on line 13```

**Comment by elizoller** [comment]
I added buffering and tested with `neu:rx917x48n` and it works

**Comment by thornomad** [comment]
Seems to be working on Safari - haven't tested it extensively though.  Thanks!  Will try and test with all browsers and platforms soon.
