### ISSUE TITLE
Collections display not working..and it used to...

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/drs-toolkit-wp-plugin#92]
http://arader.library.northeastern.edu/collections

**Comment by thornomad** [comment]
Interesting ... it works for me:

http://www.test.interpretereducation.org/tim/terptalks/collections/

Of course, that doesn't have any sub-collections ... but I tested it on my local box with another DRS series and it worked.

**Comment by elizoller** [comment]
This was a caching issue on Arader only - cannot enable "Coarse file locking." in WP super cache
