### ISSUE TITLE
Default sort order for collections

### ISSUE THREAD

**Issue by thornomad** [NEU-Libraries/drs-toolkit-wp-plugin#93]
Eli - Trudy brought this up to me ... right now when you go to `browse` the default sort order is `relevance` ... which doesn't make sense in the browse context (relevant to what?) ... it does make sense in the `search` context ...

What do you think about on the `browse` page the default sort order is date (earliest to latest) or A to Z or something ? Or, allowing the user to choose?  Thoughts?

**Comment by elizoller** [comment]
It seems once again I've managed to undo my own work....(more fuel for the test-driven development fire)
https://github.com/NEU-Libraries/drs-toolkit-wp-plugin/issues/63
The toolkit group here had decided to have browse sorted by title A-Z by default. It is easy to add this as a configuration setting though. Do you want it configurable?

**Comment by thornomad** [comment]
I think it might be nice. For us newest first would probably be best so the
stuff is available as its added.

TDD is my favorite!
