### ISSUE TITLE
Can't edit breadcrumbs in test site

### ISSUE THREAD

**Issue by sarahdelorme** [NEU-Libraries/drs-toolkit-wp-plugin#95]
![image](https://cloud.githubusercontent.com/assets/18483806/14562526/2b7cf474-02eb-11e6-8c3b-604871244a79.png)

I am trying to edit/remove the breadcrumb links from the test site and can't seem to get to them. I have been told they might be written into the theme functions.

**Comment by elizoller** [comment]
They are written programmatically. What is your goal? Do you want to remove them? If so, on which (or all) pages? If you want to edit them, how are you looking to change them?

**Comment by sarahdelorme** [comment]
I'd like to remove them on all pages.

**Comment by elizoller** [comment]
We can do this with one line of CSS or we can make it a setting to toggle on/off in the "customize" page.

**Comment by sarahjeansweeney** [comment]
I think users would like this to be a setting on the customize page.

**Comment by sarahdelorme** [comment]
excellent! I think making it a setting to toggle would be helpful for future projects as well

**Comment by elizoller** [comment]
Ok will do

**Comment by elizoller** [comment]
Fixed with https://github.com/NEU-Libraries/drs-toolkit-wp-theme/commit/b1bb90c84092344ff8234d80d5e70cc3cd151b75

**Comment by elizoller** [comment]
If you go to "Customize" then choose Layout then Global then there is a dropdown for "Show breadcrumbs" yes or no
